version: '3.8'

services:
  todo-app:
    image: todo-app-bun # Name of the image to be created
    build:
      context: . # Root of the project
      dockerfile: apps/todo/Dockerfile # Path to the Dockerfile from the context
    ports:
      - '8000:3000' # Map port 8000 on the host to port 3000 in the container
    environment:
      - DATABASE_URL=postgresql://yourdbuser:yourdbpassword@db:5432/yourdbname?schema=public
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
    ports:
      - '5432:5432' # Optional: expose PostgreSQL port for local development
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
